# Programa 1.
1. Implementa una simulación de la fábula que cuenta la carrera entre la liebre y la tortuga.

In [45]:
from threading import Thread, BoundedSemaphore
from random import randint
from time import sleep

In [46]:
class Semaforo(BoundedSemaphore):
    def __init__(self):
        self.bloqueado = False
        super().__init__()
    def block(self):
        super().acquire()
        self.bloqueado = True
    def unblocked(self):
        super().release()
        self.bloqueado = False
        
class Tortuga(Thread):
    def __init__(self, sem,casillas):
        super().__init__()
        self.sem = sem
        self.casillas = casillas
    def avanza(self):
        global casillas
        p1 = randint(1,100)
        proba = p1
        c = " "
        #print("Turno de la tortuga")
        if proba <= 50:
            casillas = self.casillas + 3
            if casillas > 70:
                casillas = 70
            #print("Avance rápido")
            #print("Avanza 3 casillas y queda en la casilla:",casillas)
            print(c*casillas,"T\n")
        if proba > 50 and proba <= 70:
            casillas = self.casillas - 6
            if casillas <1:
                casillas = 1
            #print("Resbaló")
            #print("Retrocede 6 casillas y queda en la casilla:",casillas)
            print(c*casillas,"T\n")
        if proba > 70 and proba <= 100:
            casillas = self.casillas + 1
            if casillas > 70:
                casillas = 70
            #print("Avance lento")
            #print("Avanza 1 casillas y queda en la casilla:",casillas)
            print(c*casillas,"T\n")
    def run(self):
        self.sem.block()
        self.avanza()
        sleep(1)
        self.sem.unblocked()

class Liebre(Thread):
    def __init__(self,sem,casillasl):
        super().__init__()
        self.sem = sem
        self.casillasl = casillasl
    def avanzo(self):
        global casillasl
        p2 = randint(1,100)
        proba = p2
        c = " "
        #print("Turno de la liebre")
        if proba <= 20:
            casillasl = casillasl
            #print("Duerme")
            #print("No avanza se queda en la casilla", casillasl)
            print(c*casillasl,"L\n")
        if proba > 20 and proba <= 40:
            casillasl = self.casillasl + 9
            if casillasl > 70:
                casillasl = 70
            #print("Gran salto")
            #print("Avanza 9 casillas y queda en la casilla:",casillasl)
            print(c*casillasl,"L\n")
        if proba > 40 and proba <= 50:
            casillasl = self.casillasl - 12
            if casillasl <1:
                casillasl = 1
            #print("Resbalón grande")
            #print("Retrocede 12 casillas y queda en la casilla:",casillasl)
            print(c*casillasl,"L\n")
        if proba > 50 and proba <= 80:
            casillasl = self.casillasl + 1
            if casillasl > 70:
                casillasl = 70
            #print("Pequeño salto")
            #print("Avanza 1 casillas y queda en la casilla:",casillasl)
            print(c*casillasl,"L\n")
        if proba > 80 and proba <= 100:
            casillasl = self.casillasl - 2
            if casillasl < 1:
                casillasl = 1
            #print("Resbalón pequeño")
            #print("Retrocede 2 casillas y queda en la casilla:",casillasl)
            print(c*casillasl,"L\n")
    def run(self):
        self.sem.block()
        self.avanzo()
        sleep(1)
        self.sem.unblocked()

casillasl = 1    
casillas = 1
#Random para definir el movimiento del animal.
sem = Semaforo() #Mutex es igual a la función M

print("__________Inicia carrera__________")
print(" L = Liebre y T = Tortuga.")
while casillas < 70 and casillasl < 70:
    tortuga = Tortuga(sem,casillas)
    liebre = Liebre(sem,casillasl)
    
    tortuga.start()
    liebre.start()

    tortuga.join()
    liebre.join()
    
if casillas < casillasl:
    print("Liebre ganó la carrera")
if casillas > casillasl:
    print("Tortuga ganó la carrera")
if casillas==casillasl:
    print("Hay un empate")
print("__________FIN DE LA CARRERA__________")

__________Inicia carrera__________
 L = Liebre y T = Tortuga.
   T

   L

    T

            L

       T

          L

        T

           L

           T

         L

     T

          L

        T

           L

           T

           L

            T

         L

      T

          L

         T

                   L

   T

       L

    T

        L

       T

  L

          T

   L

             T

   L

       T

   L

          T

  L

             T

   L

                T

    L

                   T

             L

             T

              L

              T

            L

        T

                     L

           T

         L

              T

         L

        T

                  L

           T

                  L

              T

                           L

                 T

                         L

           T

                          L

              T

                           L

               T

                         L

          

# Programa 2.
2. Implementar un programa secuencial que calcule el producto de dos grandes matrices (de manera convencional, es decir renglon por columna)

In [3]:
import numpy as np
from random import randint
import time
from threading import Thread

In [43]:
m = 100
n = 100
R = np.zeros((m,n))
A = np.zeros((m,n))
B = np.zeros((m,n))
t = time.time()
for Ren in range(m):
    for Col in range(n):
        x = randint(1,9)
        A[Ren][Col]= x
for Ren in range(m):
    for Col in range(n):
        y = randint(1,9)
        B[Ren][Col]= y
for i in range(len(A)):
    for j in range(len(B)):
        for k in range(len(B)):
            R[i][j] += A[i][k] * B[k][j]
print(R)
print(R.shape)
print("Tiempo de ejecución: ", time.time()-t)

[[2361. 2261. 2278. ... 2462. 2454. 2051.]
 [2701. 2608. 2715. ... 2835. 2847. 2412.]
 [2699. 2463. 2477. ... 2680. 2682. 2110.]
 ...
 [2454. 2327. 2361. ... 2449. 2500. 1920.]
 [2658. 2506. 2494. ... 2597. 2731. 2169.]
 [2471. 2439. 2525. ... 2564. 2620. 2116.]]
(100, 100)
Tiempo de ejecución:  0.7587759494781494


Después modifícalo para que esta tarea se realice en $Threads$, cada uno ocupado de un subconjunto de la matriz resultado. Mide el tiempo que emplea cada una de las versiones.

In [44]:
class matriz(Thread):
    def __init__(self,i,A,B,R):
        super().__init__()
        self.numero = i
        self.matrizA = A
        self.matrizB = B
        self.matrizR = R
    def crear(self):
        for Ren in range(m):
            for Col in range(n):
                x = randint(1,9)
                A[Ren][Col]= x
        for Ren in range(m):
            for Col in range(n):
                y = randint(1,9)
                B[Ren][Col]= y
    def multip1(self):
        R = self.matrizR
        for i in range(50):
            for j in range(50):
                for k in range(50):
                    R[i][j] += A[i][k] * B[k][j]
        print("Matriz del conjunto 1")
        print(R)
    def multip2(self):
        R = self.matrizR
        for i in range(50,100):
            for j in range(50):
                for k in range(50):
                    R[i][j] += A[i][k] * B[k][j]
        print("Matriz del conjunto 2")
        print(R)
    def multip3(self):
        R = self.matrizR
        for i in range(50):
            for j in range(50,100):
                for k in range(50):
                    R[i][j] += A[i][k] * B[k][j]
        print("Matriz del conjunto 3")
        print(R)
    def multip4(self):
        R = self.matrizR
        for i in range(100):
            for j in range(100):
                for k in range(50,100):
                    R[i][j] += A[i][k] * B[k][j]
        print("Matriz del conjunto 4")
        print(R)
    def run(self):
        self.crear()
        if self.numero == 1:
            self.multip1()
        if self.numero == 2:
            self.multip2()
        if self.numero == 3:
            self.multip3()
        if self.numero == 4:
            self.multip4()

n = 100
m = 100
R = np.zeros((m,n))
A = np.zeros((m,n))
B = np.zeros((m,n))
t = time.time()        
thread1 = matriz(1,A,B,R)
thread2 = matriz(2,A,B,R)
thread3 = matriz(3,A,B,R)
thread4 = matriz(4,A,B,R)
thread1.start()
thread1.join()
thread2.start()
thread2.join()
thread3.start()
thread3.join()
thread4.start()
thread4.join()
print("Tiempo de ejecución: ", time.time()-t)

Matriz del conjunto 1
[[1059.  985.  952. ...    0.    0.    0.]
 [1183. 1117. 1056. ...    0.    0.    0.]
 [1343. 1244. 1050. ...    0.    0.    0.]
 ...
 [   0.    0.    0. ...    0.    0.    0.]
 [   0.    0.    0. ...    0.    0.    0.]
 [   0.    0.    0. ...    0.    0.    0.]]
Matriz del conjunto 2
[[1059.  985.  952. ...    0.    0.    0.]
 [1183. 1117. 1056. ...    0.    0.    0.]
 [1343. 1244. 1050. ...    0.    0.    0.]
 ...
 [1330. 1092. 1147. ...    0.    0.    0.]
 [1386. 1149. 1105. ...    0.    0.    0.]
 [1467. 1188. 1179. ...    0.    0.    0.]]
Matriz del conjunto 3
[[1059.  985.  952. ... 1061. 1057. 1161.]
 [1183. 1117. 1056. ... 1213. 1125. 1331.]
 [1343. 1244. 1050. ... 1178. 1174. 1289.]
 ...
 [1330. 1092. 1147. ...    0.    0.    0.]
 [1386. 1149. 1105. ...    0.    0.    0.]
 [1467. 1188. 1179. ...    0.    0.    0.]]
Matriz del conjunto 4
[[2286. 2418. 2088. ... 2308. 2203. 2301.]
 [2307. 2415. 2300. ... 2363. 2208. 2441.]
 [2448. 2467. 2274. ... 2273. 2234